/* Immutable, integrity-checked application shell. See docs/PWA.md for releases. */
const VERSION = '1.5.0';
const CACHE_PREFIX = `dae-shell:${self.registration.scope}:`;
const CACHE = `${CACHE_PREFIX}${VERSION}`;
const NETWORK_TIMEOUT = 3500;
const ASSETS = [
  './', './index.html', './css/styles.css', './js/i18n.js', './js/pdf.js',
  './js/estudiantes.js', './js/app.js', './vendor/jspdf.umd.min.js',
  './js/student-import.js', './js/student-import-worker.js',
  './js/release.js',
  './vendor/xlsx.full.min.js', './plantillas/Plantilla_Estudiantes.xlsx',
  './manifest.webmanifest', './icons/icon.svg', './icons/icon-192.png',
  './icons/icon-512.png', './icons/icon-maskable-512.png', './icons/apple-touch-icon.png',
];
// Generated by tools/update-shell.cjs. Update VERSION and hashes for every release.
const INTEGRITY = {
  "./": "sha256-594tHWVEBsD7ibjMXXn/LcpvDu48wkwmIJJcsJnCGfs= sha256-73NUXGijt2Ch1zhLB52VCI11pQYebS+n97tpdBXCiiM= sha256-NmhabF19F7JbngCGhMUENO9FUnjwsueS8ywnDHcwz5A=",
  "./index.html": "sha256-594tHWVEBsD7ibjMXXn/LcpvDu48wkwmIJJcsJnCGfs= sha256-73NUXGijt2Ch1zhLB52VCI11pQYebS+n97tpdBXCiiM= sha256-NmhabF19F7JbngCGhMUENO9FUnjwsueS8ywnDHcwz5A=",
  "./css/styles.css": "sha256-Qb4uMTB8GfF5DMzVIaA2d7RkkbH8cVT4/0qON2NMMxo= sha256-miATtYLHyX3HuV5wbs7ynhvZ1Fkj0XmDmRjmqJW/i2w=",
  "./js/i18n.js": "sha256-/Ody9d3O8342ljhmNT39dYFZMksjovbEA2bm4gu69Ek= sha256-C9mPPO6nz7Vq4iV0Ri9/4mlTjHH0fh6s0CItUpCDPGo= sha256-29SCnWGLk4eKM5RyhswNHfosVBR5Ron9/tgpdxe/7ts=",
  "./js/pdf.js": "sha256-0cVqJeI5j48V5cE6ykO8avMH9iL3txltMfH6eFDRQuE= sha256-W1hSSdf2XuzT8MHCXs3CiIc1dEmWToT/47Xr6xS3+yY=",
  "./js/estudiantes.js": "sha256-zTYmWIs3gzw4exIbxhRn6ReNP2kfg8rYMwghlRTNbYU= sha256-i+qUN5v116PMeT+efjA8AK6G0cKXAED0CHhqi3kSg5Y= sha256-aI559hA2O0dId0OXY0DA+F/9wlzUGqS76Unc0prHDKI=",
  "./js/app.js": "sha256-rC1JZjNhlrvCSyHG2wvVMev0+uDl+JczzSkJV7e/u+Q= sha256-PEmJEMr3bobDjXYTLBYAYiIAvHvR1hu58hXN38P3mFA= sha256-rEatYqBO027kgRIaew105d3P0KyRRkjKYsMOFSPtd18=",
  "./vendor/jspdf.umd.min.js": "sha256-mMzxeqEMILsTAXYmGPzJtqs6Tn8mtgcdZNC0EVTfOHU= sha256-iyStrVpFZiqkDa+YvgWFXYm4oj0Mx1fWUwuj7daC78U=",
  "./js/student-import.js": "sha256-uilvgATrpeWz3xhAHSz/qObOG9aqD4adFuPiav+IUug= sha256-PEWhjEu55hawyIet1ITiFoHbQAvy0pVkh8vs3RLRy+Q= sha256-TzJ2oajXW2KQqEfzJrtc9yW2Z8DJzPJDNFU0/rEA+ss=",
  "./js/student-import-worker.js": "sha256-KBVVfSdCcHGpSYDUgOiCK3laYmMotEwBgJuIu92zC30= sha256-XJtqV92l8Plj3T8wODHTPim7I0aCrUKNuLOgO9AElB0=",
  "./js/release.js": "sha256-pGltwCXaQ/Y16ISsmlDnX6daEkpygiPU/OTkpfGOWL8= sha256-nIDAXKRWmm06IY4QPzCSFOnNn+FgmHIo6OWv77eFrBs=",
  "./vendor/xlsx.full.min.js": "sha256-zAFRMKqFIefwiPiImOupSczcv7ON8L0Sm0S3Jzw6b0E= sha256-rI13TTm7BaUn+HkS4sKD4jfjYzEgsxrPILxu7w4Z7t4=",
  "./plantillas/Plantilla_Estudiantes.xlsx": "sha256-lvji/uWAcZuS768FItHCKtCuPcunWJ0yJpBAoMgdTk8=",
  "./manifest.webmanifest": "sha256-r+qF03Nuh4Ske+7CKVJzAS4EOIiWBLXCTAFvtHJ/9Jg= sha256-FUE8rnzSB2tXMbIRD3iTTg8HwBAPcmH1Ra38edRpnI0=",
  "./icons/icon.svg": "sha256-fNAovNHD2TLzmmRXUEZWrAtA7Y+LTBRylvyqj2fZRfQ=",
  "./icons/icon-192.png": "sha256-k/vpTw1tmexAYhSI51uvAPQTFF7dOD6D9x5EGcVdopY=",
  "./icons/icon-512.png": "sha256-izrYhxG9CMsnTQQ839RKIckgVZK/lp+udBLNfUkJAQA=",
  "./icons/icon-maskable-512.png": "sha256-FO9y0UQsQ3tx3v3YpZiY01JmapFZazTrgo7A2tiFU2o=",
  "./icons/apple-touch-icon.png": "sha256-x0Uf8o5qTfDT75BtOJWeO3cuERQsdY4LTy3VAYM2MqI="
};
const shellUrls = new Set(ASSETS.map(asset => new URL(asset, self.registration.scope).href));

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    try {
      const cache = await caches.open(CACHE);
      await cache.addAll(ASSETS.map(asset => new Request(new URL(asset, self.registration.scope), {
        cache: 'reload', integrity: INTEGRITY[asset],
      })));
    } catch (error) {
      await caches.delete(CACHE);
      throw error;
    }
  })());
  // Wait for all existing controlled windows to close; never interrupt an open form.
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.map(async key => {
      if (key.startsWith(CACHE_PREFIX) && key !== CACHE) await caches.delete(key);
      // Retire this application's old network-first cache, preserving other scopes.
      if (/^dae-\d+\.\d+\.\d+$/.test(key)) {
        const legacy = await caches.open(key);
        if (await legacy.match(new URL('./index.html', self.registration.scope).href)) await caches.delete(key);
      }
    }));
  })());
  // No clients.claim(): an uncontrolled document may already contain another release.
});

self.addEventListener('fetch', event => {
  const req = event.request;
  // Exact URL allowlist: queries, unknown routes, uploads and generated content bypass us.
  if (req.method !== 'GET' || !shellUrls.has(req.url) || req.headers.has('range')) return;
  event.respondWith(shellResponse(req));
});

async function shellResponse(req) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(req);
  if (cached?.ok) return cached;
  // A missing shell entry must not be filled with a possibly different release.
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), NETWORK_TIMEOUT);
  try {
    const asset = ASSETS.find(path => new URL(path, self.registration.scope).href === req.url);
    const response = await fetch(req, { signal: controller.signal, integrity: INTEGRITY[asset] });
    if (response.status >= 500 && response.status <= 599) {
      const fallback = await cache.match(req);
      if (fallback?.ok) return fallback;
    }
    return response; // Preserve legitimate 404 and other client errors.
  } catch (_) {
    const fallback = await cache.match(req);
    return fallback?.ok ? fallback : Response.error();
  } finally {
    clearTimeout(timer);
  }
}
