/* Immutable, integrity-checked application shell. See docs/PWA.md for releases. */
const VERSION = '1.4.0';
const CACHE_PREFIX = `dae-shell:${self.registration.scope}:`;
const CACHE = `${CACHE_PREFIX}${VERSION}`;
const NETWORK_TIMEOUT = 3500;
const ASSETS = [
  './', './index.html', './css/styles.css', './js/i18n.js', './js/pdf.js',
  './js/estudiantes.js', './js/app.js', './vendor/jspdf.umd.min.js',
  './vendor/xlsx.full.min.js', './plantillas/Plantilla_Estudiantes.xlsx',
  './manifest.webmanifest', './icons/icon.svg', './icons/icon-192.png',
  './icons/icon-512.png', './icons/icon-maskable-512.png', './icons/apple-touch-icon.png',
];
// Generated by tools/update-shell.cjs. Update VERSION and hashes for every release.
const INTEGRITY = {
  "./": "sha256-Vi7GTx5fkuo49F7NsageHT1dIO1O1YIUI+dMAEfGheg= sha256-Ps2Vt+JwaG55IKUpoXzIvDIGccx0yhWDkvJ93HmBKqU=",
  "./index.html": "sha256-Vi7GTx5fkuo49F7NsageHT1dIO1O1YIUI+dMAEfGheg= sha256-Ps2Vt+JwaG55IKUpoXzIvDIGccx0yhWDkvJ93HmBKqU=",
  "./css/styles.css": "sha256-DAyklZ74cr2rXfUIQhax9dj1ySqK5u3BV8fnLwdgvIg= sha256-R8C7iIaknLfhFoCueAWI1yVN2U+P1Sx869vISOP8unU=",
  "./js/i18n.js": "sha256-5NRxD+2TrhSr1muLMHW78Xig3HaY0iy/1D2XmfuFdBs= sha256-TSZ5tqAZ1Q4SUgtUqIhv3tP3aEZxBs+FDp1irOaBkIk= sha256-3JVlVhU9cDBpxdE95Z56TaQvLNaPCmO2x3T3PPJwYfo=",
  "./js/pdf.js": "sha256-0cVqJeI5j48V5cE6ykO8avMH9iL3txltMfH6eFDRQuE= sha256-W1hSSdf2XuzT8MHCXs3CiIc1dEmWToT/47Xr6xS3+yY=",
  "./js/estudiantes.js": "sha256-8OerunRjrXBXfdHdunxLI5LH/L5zSpcZn/qiUBbSxXA= sha256-lNRjES4rVmucDYxGQqkPQ0zE7SrL+UbLT2tffhJv85U= sha256-fDpbsMoYbWqHDc8U8bv4TXNFSssep8E/Mmjg+Kl4Sfw=",
  "./js/app.js": "sha256-9n3AzCSgBuZiTt8+dcNVvzLe+6Vxeyv8aVbB+Qh63bw= sha256-u5ElI5WZWMJ3CgMPhqZqDFni7y9Zvjh2JfpLWpUmvx8=",
  "./vendor/jspdf.umd.min.js": "sha256-mMzxeqEMILsTAXYmGPzJtqs6Tn8mtgcdZNC0EVTfOHU= sha256-iyStrVpFZiqkDa+YvgWFXYm4oj0Mx1fWUwuj7daC78U=",
  "./vendor/xlsx.full.min.js": "sha256-zAFRMKqFIefwiPiImOupSczcv7ON8L0Sm0S3Jzw6b0E= sha256-rI13TTm7BaUn+HkS4sKD4jfjYzEgsxrPILxu7w4Z7t4=",
  "./plantillas/Plantilla_Estudiantes.xlsx": "sha256-0mRpYXuGX6SKZmHYzlgx9TMf734Iq5CMp0+NXTZ46X0=",
  "./manifest.webmanifest": "sha256-r+qF03Nuh4Ske+7CKVJzAS4EOIiWBLXCTAFvtHJ/9Jg= sha256-FUE8rnzSB2tXMbIRD3iTTg8HwBAPcmH1Ra38edRpnI0=",
  "./icons/icon.svg": "sha256-fNAovNHD2TLzmmRXUEZWrAtA7Y+LTBRylvyqj2fZRfQ=",
  "./icons/icon-192.png": "sha256-k/vpTw1tmexAYhSI51uvAPQTFF7dOD6D9x5EGcVdopY=",
  "./icons/icon-512.png": "sha256-izrYhxG9CMsnTQQ839RKIckgVZK/lp+udBLNfUkJAQA=",
  "./icons/icon-maskable-512.png": "sha256-FO9y0UQsQ3tx3v3YpZiY01JmapFZazTrgo7A2tiFU2o=",
  "./icons/apple-touch-icon.png": "sha256-x0Uf8o5qTfDT75BtOJWeO3cuERQsdY4LTy3VAYM2MqI="
};
const shellUrls = new Set(ASSETS.map(asset => new URL(asset, self.registration.scope).href));

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    try {
      const cache = await caches.open(CACHE);
      await cache.addAll(ASSETS.map(asset => new Request(new URL(asset, self.registration.scope), {
        cache: 'reload', integrity: INTEGRITY[asset],
      })));
    } catch (error) {
      await caches.delete(CACHE);
      throw error;
    }
  })());
  // Wait for all existing controlled windows to close; never interrupt an open form.
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.map(async key => {
      if (key.startsWith(CACHE_PREFIX) && key !== CACHE) await caches.delete(key);
      // Retire this application's old network-first cache, preserving other scopes.
      if (/^dae-\d+\.\d+\.\d+$/.test(key)) {
        const legacy = await caches.open(key);
        if (await legacy.match(new URL('./index.html', self.registration.scope).href)) await caches.delete(key);
      }
    }));
  })());
  // No clients.claim(): an uncontrolled document may already contain another release.
});

self.addEventListener('fetch', event => {
  const req = event.request;
  // Exact URL allowlist: queries, unknown routes, uploads and generated content bypass us.
  if (req.method !== 'GET' || !shellUrls.has(req.url) || req.headers.has('range')) return;
  event.respondWith(shellResponse(req));
});

async function shellResponse(req) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(req);
  if (cached?.ok) return cached;
  // A missing shell entry must not be filled with a possibly different release.
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), NETWORK_TIMEOUT);
  try {
    const asset = ASSETS.find(path => new URL(path, self.registration.scope).href === req.url);
    const response = await fetch(req, { signal: controller.signal, integrity: INTEGRITY[asset] });
    if (response.status >= 500 && response.status <= 599) {
      const fallback = await cache.match(req);
      if (fallback?.ok) return fallback;
    }
    return response; // Preserve legitimate 404 and other client errors.
  } catch (_) {
    const fallback = await cache.match(req);
    return fallback?.ok ? fallback : Response.error();
  } finally {
    clearTimeout(timer);
  }
}
